### ISSUE TITLE
[npm ERR]Unexpected end of JSON input while parsing near '..."size":326897,"noatta'

### ISSUE THREAD

**Issue by TonyLuo** [oktadeveloper/ionic-jhipster-starter#13]
I run  into npm ERR when run npm install command , 

commands :
ionic start ionic4j oktadeveloper/jhipster
cd ionic4j/
npm i

error: 
```
✖ Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        
        npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
        npm ERR! Unexpected end of JSON input while parsing near '..."size":326897,"noatta'

MacBook-Air:ionic4j tony$ npm i
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '..."size":326897,"noatta'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2018-06-24T16_04_44_917Z-debug.log


/.npm/_logs/2018-06-24T16_04_44_917Z-debug.log

2301 silly saveTree ├── typescript@2.8.1
2301 silly saveTree └── zone.js@0.8.26
2302 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."size":326897,"noatta'
2302 verbose stack     at JSON.parse (<anonymous>)
2302 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
2302 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
2302 verbose stack     at <anonymous>
2302 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
2303 verbose cwd /Users/tony/dev/ionic/ionic4j
2304 verbose Darwin 17.6.0
2305 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
2306 verbose node v8.11.3
2307 verbose npm  v5.6.0
2308 error Unexpected end of JSON input while parsing near '..."size":326897,"noatta'
2309 verbose exit [ 1, true ]
```

**Comment by TonyLuo** [comment]
it is npm error, i solve it by running this command : npm cache clean --force

**Comment by mraible** [comment]
Thanks for following up with the solution!
